spark.master                     yarn
spark.driver.memory               4g
spark.yarn.am.memory             1g
spark.executor.memory            2g
spark.executor.instances         2
spark.yarn.jars                  hdfs:///spark/jars/*
spark.yarn.archive              hdfs:///spark/spark-libs.jar
spark.hadoop.yarn.resourcemanager.hostname yarn-resourcemanager
spark.hadoop.yarn.resourcemanager.address yarn-resourcemanager:8032
spark.hadoop.yarn.resourcemanager.scheduler.address yarn-resourcemanager:8030
spark.hadoop.yarn.resourcemanager.resource-tracker.address yarn-resourcemanager:8031
spark.hadoop.yarn.resourcemanager.webapp.address yarn-resourcemanager:8088